export const searchActionTypes = {
  CATEGORY_SELECT_ONLY: "CATEGORY_SELECT_ONLY",
  CATEGORY_SELECT: "CATEGORY_SELECT",
  DISCOUNT_SELECT_ONLY: "DISCOUNT_SELECT_ONLY",
  DISCOUNT_SELECT: "DISCOUNT_SELECT",
  POPULAR_SELECT_ONLY: "POPULAR_SELECT_ONLY",
  POPULAR_SELECT: "POPULAR_SELECT",
};
